if: type = pull_request
language: go
jdk:
  - openjdk8
go:
  - 1.12.x
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  - GO111MODULE=on
before_install:
  - npm i -g npm
  - mkdir -p $HOME/gopath/src/github.com/cellery-io
  - mv ${TRAVIS_BUILD_DIR} $GOPATH/src/github.com/cellery-io/mesh-observability
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cellery-io/mesh-observability
  - cd $HOME/gopath/src/github.com/cellery-io/mesh-observability
script:
  - make clean.mixer-adapter check-style.mixer-adapter build.mixer-adapter test.mixer-adapter
  - mvn clean install -q
  - make docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
