if: type = pull_request
dist: trusty
language: go
jdk:
  - openjdk8
go:
  - 1.12.x
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  - GO111MODULE=on
before_install:
  - npm i -g npm
script:
  - make clean.mixer-adapter check-style.mixer-adapter build.mixer-adapter test.mixer-adapter
  - travis_wait 30 mvn clean install
  - make docker
after_success:
  - bash <(curl -s https://codecov.io/bash)
